### ISSUE TITLE
Small spelling mistake in function name (continuous_corrmax) causing error in Outliers

### ISSUE THREAD

**Issue by llim-baycrest** [derekbeaton/OuRS#19]
One of the function names in the OuRS package was misspelled and causing an error in the Outliers app, namely the function supposed to be named **continuous_corrmax** was written as "continous_corrmax" (the 'u' was missing) in the OuRS package. Should I just change the name in the Outliers app?

In files: corrmaxs.R, continous_corrmax.Rd, NAMESPACE

@derekbeaton

**Comment by derekbeaton** [comment]
fixed, thanks. closing issue now

**Comment by llim-baycrest** [comment]
Oops, sorry Derek, didn't catch this because I was building OuRS from source while I was waiting, but found out today when trying to reinstall from the repo that the export in NAMESPACE still has the wrong spelling.

**Comment by derekbeaton** [comment]
ok now it should be fixed, sorry!
