### ISSUE TITLE
Reproducibility of mcd

### ISSUE THREAD

**Issue by emafin** [derekbeaton/OuRS#25]
Hello, thank you for this package. I am trying to replicate a solution obtained through  `categorical_mcd` across repeated runs. I wonder if there is a way to set seed when using the function; sorry if I am missing anything. I am providing a reproducible example, below. 

Thank you in advance for any help you may offer. 

```
# Load packages
library(tidyverse)
library(ours)

# MCD
mcd1 <- iris %>%
  data.frame(.) %>% 
  select(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) %>% 
  as.matrix(.) %>% 
  categorical_mcd(., alpha = 0.5)

# Same, save as mcd2
mcd2 <- iris %>%
  data.frame(.) %>% 
  select(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) %>% 
  as.matrix(.) %>% 
  categorical_mcd(., alpha = 0.5)

# Cut-off
cut <- sqrt(qchisq(0.01, ncol(select(iris, starts_with("Sepal"), starts_with("Petal"))), lower.tail = FALSE))

# Outliers detection
mcd1$dists$robust_mahal_dists > cut 
mcd2$dists$robust_mahal_dists > cut
```

**Comment by derekbeaton** [comment]
I think you can set the seed before each run with set.seed()

An unrelated note: the iris data are continuous so the categorical MCD is not appropriate for those data. It will treat every unique value as a level in the category.
